/**
 * Fixed till-slip / SMS copy.
 *
 * Figures, KES amounts, dates and item names are interpolated later and
 * never sent through Gemini. Only these surrounding strings are localised.
 * Swahili is a checked-in template so a weekly report does not depend on
 * a live translation call. Gemini is reserved for languages we do not
 * have a template for, and for phrasing extra prose (compliance notices).
 */

export const REPORT_LABELS = {
  en: {
    weeklyTitle: 'BiasharaBot Weekly Report',
    dailyTitle: 'BiasharaBot Daily Report',
    shop: 'Shop',
    weeklySubtitle: 'WEEKLY REPORT',
    dailySubtitle: 'DAILY REPORT',
    productsSold: 'PRODUCTS SOLD',
    period: 'Period',
    date: 'Date',
    phone: 'Phone',
    till: 'Till',
    qty: 'Qty',
    price: 'Price',
    revenue: 'REVENUE',
    costOfGoods: 'COST OF GOODS (PURCHASES)',
    otherExpenses: 'OTHER EXPENSES',
    mpesaFees: 'M-PESA CHARGES (PAYHERO)',
    netProfit: 'NET PROFIT',
    grossProfit: 'GROSS PROFIT',
    grossProfitByItem: 'GROSS PROFIT BY ITEM',
    outstandingCredit: 'OUTSTANDING CREDIT',
    poweredBy: 'Powered by BiasharaBot!',
    printedAt: 'Printed at',
    noSales: 'No sales this week yet.',
    itemsMissingCost: '{count} sold item(s) have no stock cost yet',
    noCostYet: 'NO COST YET',
    sold: 'sold',
    rev: 'rev',
    cost: 'cost',
    addStockForMargin: 'add stock to see margin',
    grossNote: 'Cost of goods sold uses the unit cost you recorded on Stock. Net profit above is still cash in minus cash out.',
    languageFallbackNote: 'Showing English — translation was unavailable.'
  },
  sw: {
    weeklyTitle: 'Ripoti ya Wiki ya BiasharaBot',
    dailyTitle: 'Ripoti ya Siku ya BiasharaBot',
    shop: 'Duka',
    weeklySubtitle: 'RIPOTI YA WIKI',
    dailySubtitle: 'RIPOTI YA SIKU',
    productsSold: 'BIDHAA ZILIZOUZWA',
    period: 'Kipindi',
    date: 'Tarehe',
    phone: 'Simu',
    till: 'Till',
    qty: 'Idadi',
    price: 'Bei',
    revenue: 'MAUZO',
    costOfGoods: 'GHARAMA YA BIDHAA (MANUNUZI)',
    otherExpenses: 'GHARAMA NYINGINE',
    mpesaFees: 'ADA ZA M-PESA (PAYHERO)',
    netProfit: 'FAIDA HALISI',
    grossProfit: 'FAIDA GHAFI',
    grossProfitByItem: 'FAIDA GHAFI KWA BIDHAA',
    outstandingCredit: 'DENI LINALOSUBIRI',
    poweredBy: 'Imewezeshwa na BiasharaBot!',
    printedAt: 'Imeandikwa',
    noSales: 'Hakuna mauzo wiki hii bado.',
    itemsMissingCost: 'Bidhaa {count} zilizouzwa bado hazina gharama ya stock',
    noCostYet: 'HAKUNA GHARAMA BADO',
    sold: 'zimeuzwa',
    rev: 'mauzo',
    cost: 'gharama',
    addStockForMargin: 'ongeza stock kuona faida',
    grossNote: 'Gharama ya bidhaa zilizouzwa inatumia bei uliyorekodi kwenye Stock. Faida halisi hapo juu bado ni pesa iliyoingia kutoa pesa iliyotoka.',
    languageFallbackNote: 'Inaonyesha Kiingereza — tafsiri haikupatikana.'
  }
};

export const COMPLIANCE_LABELS = {
  en: {
    heading: 'Tax and business compliance',
    intro: 'What applies to your shop from the details you gave us, plus sales already on the ledger. Figures and dates come from KRA / county rules — not from the AI.',
    profileHeading: 'Your shop profile',
    profileHint: 'A few details decide which obligations apply. Existing shops start with safe defaults until you fill these in.',
    incompleteBanner: 'Finish your shop profile to see the tax and permit deadlines that apply to you.',
    completeProfile: 'Complete profile',
    businessType: 'Business type',
    soleProprietor: 'Sole proprietor',
    partnership: 'Partnership',
    company: 'Company',
    county: 'County',
    countyPlaceholder: 'Select county',
    kraPin: 'Do you have a KRA PIN?',
    kraUnknown: 'Not sure yet',
    kraYes: 'Yes',
    kraNo: 'Not yet',
    estimatedTurnover: 'Estimated annual turnover (KSh)',
    saveProfile: 'Save profile',
    applies: 'Applies',
    notApplicable: 'Does not apply',
    statusOk: 'On track',
    statusAction: 'Action needed',
    statusUpcoming: 'Deadline soon',
    statusOverdue: 'Deadline passed',
    nextDeadline: 'Next deadline',
    noDeadline: 'No fixed date',
    ledgerTurnover: 'Ledger sales (12 months)',
    usedTurnover: 'Turnover used for rules',
    noticesHeading: 'Notices sent',
    noNotices: 'No SMS notices sent yet this window.',
    kraPinTitle: 'KRA PIN registration',
    kraPinBody: 'Every business needs a KRA PIN to file tax and to use M-Pesa till tools properly. Register on iTax if you do not have one.',
    totTitle: 'Turnover Tax (TOT)',
    totBody: 'TOT applies when yearly turnover is above KSh {min} and not more than KSh {max}. It is filed monthly at {rate}%. Next filing is due by {deadline}.',
    vatTitle: 'VAT registration',
    vatBody: 'You must register for VAT once taxable supplies reach KSh {threshold} in a 12-month period. Register on iTax before you cross it if you are close.',
    etimsTitle: 'eTIMS electronic invoicing',
    etimsBody: 'KRA requires electronic tax invoices (eTIMS) for businesses that should be issuing invoices — especially once VAT applies. Enrol on the KRA eTIMS portal.',
    permitTitle: 'County single business permit',
    permitBody: 'Your county issues a single business permit, renewed every year. For {county} the next renewal we are tracking is {deadline}. Confirm the exact date with the county offices.',
    permitBodyNoCounty: 'Your county issues a single business permit, renewed every year. Pick your county in the shop profile so we can show the right deadline.',
    incomeTaxTitle: 'Annual income tax return',
    incomeTaxBody: 'File your income tax return on iTax by {deadline} for the previous year of income. Keep the weekly till slip — it is the record you will need.',
    thresholdTot: 'Your turnover has entered the Turnover Tax band (above KSh {min}).',
    thresholdVat: 'Your turnover has reached the VAT registration threshold (KSh {threshold}).',
    deadlineSms: 'BiasharaBot: {title} — due {deadline}. {hint}',
    newObligationSms: 'BiasharaBot: {title} now applies to {shop}. {hint}'
  },
  sw: {
    heading: 'Uzingatiaji wa kodi na biashara',
    intro: 'Wajibu unaokuhusu kutokana na taarifa za duka lako, pamoja na mauzo kwenye leja. Tarehe na kiasi vinatoka kwenye sheria za KRA / kaunti — si kutoka kwa AI.',
    profileHeading: 'Wasifu wa duka lako',
    profileHint: 'Maelezo machache yanaamua wajibu gani unahusu. Maduka yaliyopo yanaanza na chaguo salama hadi ujajaze haya.',
    incompleteBanner: 'Kamilisha wasifu wa duka ili kuona tarehe za kodi na leseni zinazokuhusu.',
    completeProfile: 'Kamilisha wasifu',
    businessType: 'Aina ya biashara',
    soleProprietor: 'Mmiliki mmoja',
    partnership: 'Ushirika',
    company: 'Kampuni',
    county: 'Kaunti',
    countyPlaceholder: 'Chagua kaunti',
    kraPin: 'Je, una PIN ya KRA?',
    kraUnknown: 'Sijaamua',
    kraYes: 'Ndiyo',
    kraNo: 'Bado',
    estimatedTurnover: 'Mauzo ya mwaka yaliyokadiriwa (KSh)',
    saveProfile: 'Hifadhi wasifu',
    applies: 'Inahusu',
    notApplicable: 'Haihusu',
    statusOk: 'Iko sawa',
    statusAction: 'Inahitaji hatua',
    statusUpcoming: 'Tarehe inakaribia',
    statusOverdue: 'Tarehe imepita',
    nextDeadline: 'Tarehe inayofuata',
    noDeadline: 'Hakuna tarehe maalum',
    ledgerTurnover: 'Mauzo kwenye leja (miezi 12)',
    usedTurnover: 'Mauzo yanayotumika kwenye sheria',
    noticesHeading: 'Arifa zilizotumwa',
    noNotices: 'Hakuna SMS iliyotumwa katika kipindi hiki.',
    kraPinTitle: 'Usajili wa PIN ya KRA',
    kraPinBody: 'Kila biashara inahitaji PIN ya KRA kuwasilisha kodi na kutumia till ya M-Pesa. Jisajili kwenye iTax ikiwa huna.',
    totTitle: 'Kodi ya Mauzo (TOT)',
    totBody: 'TOT inahusu mauzo ya mwaka yakiwa juu ya KSh {min} na yasiyozidi KSh {max}. Inawasilishwa kila mwezi kwa {rate}%. Tarehe inayofuata ni {deadline}.',
    vatTitle: 'Usajili wa VAT',
    vatBody: 'Lazima ujisajili kwa VAT mauzo yanapofika KSh {threshold} katika miezi 12. Jisajili kwenye iTax ukikaribia kizingiti hicho.',
    etimsTitle: 'Ankara za kielektroniki eTIMS',
    etimsBody: 'KRA inahitaji ankara za kielektroniki (eTIMS) kwa biashara zinazotoa ankara — hasa VAT inapohusu. Jisajili kwenye tovuti ya eTIMS ya KRA.',
    permitTitle: 'Leseni moja ya biashara ya kaunti',
    permitBody: 'Kaunti yako hutoa leseni moja ya biashara, inayofanywa upya kila mwaka. Kwa {county} tarehe tunayofuata ni {deadline}. Thibitisha tarehe kamili ofisini kwa kaunti.',
    permitBodyNoCounty: 'Kaunti hutoa leseni moja ya biashara kila mwaka. Chagua kaunti yako kwenye wasifu ili tuonyeshe tarehe sahihi.',
    incomeTaxTitle: 'Marejesho ya kodi ya mwaka',
    incomeTaxBody: 'Wasilisha marejesho ya kodi kwenye iTax kufikia {deadline} kwa mwaka uliopita wa mapato. Hifadhi ripoti ya wiki — ndiyo kumbukumbu utakayohitaji.',
    thresholdTot: 'Mauzo yako yameingia kwenye kiwango cha TOT (juu ya KSh {min}).',
    thresholdVat: 'Mauzo yako yamefika kizingiti cha usajili wa VAT (KSh {threshold}).',
    deadlineSms: 'BiasharaBot: {title} — tarehe {deadline}. {hint}',
    newObligationSms: 'BiasharaBot: {title} sasa inahusu {shop}. {hint}'
  }
};

export function interpolate(template, vars = {}) {
  return String(template || '').replace(/\{(\w+)\}/g, (_, key) => (
    vars[key] === undefined || vars[key] === null ? '' : String(vars[key])
  ));
}
