import mongoose from 'mongoose';

const entrySchema = new mongoose.Schema({
  business_id: { type: String, required: true, default: 'demo-shop' },
  type: { type: String, enum: ['sale', 'purchase', 'expense', 'credit'], required: true },
  item: { type: String, required: true },
  qty: { type: Number, required: true },
  unit_price: { type: Number, required: true },
  total: { type: Number, required: true },
  source: { type: String, enum: ['voice', 'text', 'payhero'], required: true },
  transcription: { type: String },
  matched: { type: Boolean, default: false },
  // Idempotency key generated by the PWA for entries captured offline. The app
  // and its service worker can both retry the same upload, so this is what
  // stops one sale being written twice. Sparse: entries logged online omit it.
  client_id: { type: String, unique: true, sparse: true },
  // Audit trail: the id of the placeholder M-Pesa payment this entry absorbed
  // when it finally synced (see reconcileOfflineSale in server.js).
  reconciled_from: { type: String },
  timestamp: { type: Date, default: Date.now }
});

const Entry = mongoose.model('Entry', entrySchema);
export default Entry;
